### ISSUE TITLE
Sprites missing foreground and background

### ISSUE THREAD

**Issue by matshou** [AlbertTheTerrible/Mushroom-Dream#13]
Game throws errors about sprites not having valid foreground and background.

Tileset Tag: [13-01-2022](https://github.com/AlbertTheTerrible/Mushroom-Dream/releases/tag/13-01-2022)
Game Version: `0.F-5477-ge3971b805c`

```
ERROR SDL : D:\Projects\Cataclysm-DDA\src\cata_tiles.cpp:732: tile player_rev1 has no (valid) foreground nor background
ERROR SDL : D:\Projects\Cataclysm-DDA\src\cata_tiles.cpp:732: tile t_grass_tall_season_winter has no (valid) foreground nor background
```

**Comment by AlbertTheTerrible** [comment]
Hmm, i'm gonna have to ask what those errors mean

**Comment by AlbertTheTerrible** [comment]
I made a new release that hopefully fixes this issue. Lemme know if it's working properly so i can close this👍

I'm also changing the download links so that there's no more conflicts with the licensing. 
Thank you for the help ❤

**Comment by AlbertTheTerrible** [comment]
Forgot to post the link, [so here ya go](https://www.patreon.com/posts/new-release-24-61562944?utm_medium=clipboard_copy&utm_source=copy_to_clipboard&utm_campaign=postshare) 😁

**Comment by matshou** [comment]
The errors are no longer showing up in the newest version.

**Comment by AlbertTheTerrible** [comment]
Just wanna thank @ZhilkinSerg for pointing out what the issue was, otherwise I was probably still trying to figure out what was wrong 👍
