### ISSUE TITLE
No 'unknown' tile defined

### ISSUE THREAD

**Issue by matshou** [AlbertTheTerrible/Mushroom-Dream#18]
The following error occurs when the tileset is selected and applied from game options:

```
cata_tiles.cpp:740: The tileset you're using has no 'unknown' tile defined!
```

**Comment by AlbertTheTerrible** [comment]
Is that on the mashup on on the base mushroom dream?

**Comment by matshou** [comment]
Mushroom Mashup tileset.

**Comment by AlbertTheTerrible** [comment]
i added an unknown.png, this should be fixed on the next release

thanks @Fris0uman for the help 👍

**Comment by AlbertTheTerrible** [comment]
Let me know if this issue remains with the new release 👍
