### ISSUE TITLE
tile_config.json is missing

### ISSUE THREAD

**Issue by Dandriatz** [AlbertTheTerrible/Mushroom-Dream#6]
When i try to select the tileset from option a get a message: "tile_config.json is missing"
i cant even find this file in the repo

**Comment by Helldrone** [comment]
Same issue here.

**Comment by AlbertTheTerrible** [comment]
Hmm, lemme check

**Comment by AlbertTheTerrible** [comment]
Here's the missing file. I'll update the release soon and hopefully i wont forget that file again. Sorry about that. 

Just gotta change the extention to .json instead of txt
[tile_config.txt](https://github.com/AlbertTheTerrible/Mushroom-Dream/files/7558438/tile_config.txt)

**Comment by AlbertTheTerrible** [comment]
Let me know if it's working for you guys so i can close it 👍

**Comment by AlbertTheTerrible** [comment]
I am closing this because i'm making a new release soon, hopefully with no problems x)
